server:
  port: 8080

spring:
  application:
    name: ibnfirnas-backend

  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/ibnfirnas_db
    username: postgres
    password: Aliya57
    driver-class-name: org.postgresql.Driver

  # JPA / Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  # DevTools
  devtools:
    restart:
      enabled: true

  # Email Configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: mohdanwarwind@gmail.com
    password: lmbzuauinchphamt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# JWT Configuration
jwt:
  secret: ibnfirnas-super-secret-key-2024-must-be-at-least-256-bits-long
  expiration: 86400000

# Swagger
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

# Logging
logging:
  level:
    com.ibnfirnas: DEBUG
    org.springframework.security: DEBUG